# Generated by Django 2.0.5 on 2018-05-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('sentiment', models.IntegerField(blank=True, default=-1)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
