# Generated by Django 2.0.5 on 2018-05-21 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieclassifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 21, 16, 30, 50, 376689), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.IntegerField(blank=True),
        ),
    ]
