# Generated by Django 2.0.5 on 2018-05-21 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieclassifier', '0002_auto_20180521_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 21, 16, 47, 34, 65993), verbose_name='date published'),
        ),
    ]
