# Generated by Django 2.0.5 on 2018-05-21 10:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieclassifier', '0003_auto_20180521_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 21, 19, 0, 2, 907344), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
    ]
