# Generated by Django 2.0.5 on 2018-05-21 10:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieclassifier', '0004_auto_20180521_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 21, 19, 31, 41, 589030), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
    ]
